### ISSUE TITLE
Fails to compile on Mac OS Mountain Lion: error: 'unordered_map' file not found

### ISSUE THREAD

**Issue by sjackman** [pachterlab/kallisto#36]
If this file is required, perhaps the cmake test could check and produce a better error message.

See http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1857/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_Homebrew_science_kallisto/
```
cd /tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src && /usr/local/Library/ENV/4.3/clang++    -I/tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/../ext -I/tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src -I/usr/local/include    -std=c++11 -O3 -o CMakeFiles/kallisto_core.dir/Kmer.cpp.o -c /tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/Kmer.cpp
In file included from /tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/H5Writer.cpp:1:
In file included from /tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/H5Writer.h:4:
In file included from /tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/EMAlgorithm.h:5:
/tmp/kallisto20150506-92455-1q2gpzh/kallisto-0.42/src/KmerIndex.h:8:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
         ^
```

**Comment by pimentel** [comment]
Hi @sjackman this is actually a C++11 feature that I'm willing to bet isn't available in the Mountain Lion compiler. I think we need to check whether the compiler is compatible with the C++11 feature we use. I'm not sure if there is a workaround for older compilers. We'll look into it. Thanks for the report!

**Comment by pmelsted** [comment]
Fixed in homebrew.

**Comment by sjackman** [comment]
> Fixed in homebrew.

Hmm? Not as far as I know. The bottle is still missing for Mountain Lion.
https://github.com/Homebrew/homebrew-science/blob/master/kallisto.rb#L10-L11

**Comment by pmelsted** [comment]
Can't be fixed since we require c++11
